# Generated by Django 2.2.1 on 2019-10-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_fac_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course_fac_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_request', models.IntegerField(blank=True, null=True)),
                ('course_respond', models.IntegerField(blank=True, null=True)),
                ('course_percent', models.IntegerField(blank=True, null=True)),
                ('course_perform', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_faculty_id', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_video_title', models.CharField(blank=True, max_length=100, null=True)),
                ('course_video', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Course Videos',
            },
        ),
        migrations.CreateModel(
            name='QueryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_std_id', models.CharField(blank=True, max_length=100, null=True)),
                ('query_fac_id', models.CharField(blank=True, max_length=100, null=True)),
                ('query_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('query_data', models.TextField(blank=True, null=True)),
                ('query_data_ans', models.TextField(blank=True, null=True)),
                ('query_solved', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Query Form',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_std_id', models.CharField(blank=True, max_length=100, null=True)),
                ('att_std_name', models.CharField(blank=True, max_length=100, null=True)),
                ('att_tot_vid', models.IntegerField(blank=True, null=True)),
                ('att_seen_vid', models.IntegerField(blank=True, null=True)),
                ('att_percent', models.IntegerField(blank=True, null=True)),
                ('att_perform', models.CharField(blank=True, max_length=100, null=True)),
                ('att_exam', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Student Attendance',
            },
        ),
        migrations.CreateModel(
            name='StudentCourseAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_std_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_std_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_course_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('rep_attend', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Student Course Attend',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('user_roll_no', models.CharField(blank=True, max_length=100, null=True)),
                ('user_role', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
